# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('measure', models.CharField(max_length=64)),
                ('expiration_date', models.DateField()),
                ('is_expiration_estimated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('estimated_shelf_life', models.IntegerField()),
                ('preferred_measure_type', models.CharField(choices=[('W', 'WEIGHT'), ('V', 'VOLUME')], max_length=16)),
                ('density', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IngredientType'),
        ),
    ]
